package com.java8.test.exceptions;

public class ThrowArithmeticEx {
	public static void main(String args[]) {
		/*int a = 10;
		int y = a++;

		int z = y--;
		int x1 = a - 2*y - z;
		System.out.println(x1);
		int x2 = a - 11;
		System.out.println(x2);
		int x = x1/ x2;
		System.out.println(x);
*/

		/*int x = (int)(7.3/10.6);
		int y = (int)(100.76/123.87);
		System.out.println(x);System.out.println(y);
		int z = x/y;
		System.out.println(x);
*/

		/*System.out.println(77.0/0);*/
		
		
		/*System.out.println(-77.0/0);*/
		
		/*System.out.println(0.0/0);*/
		
		/*System.out.println(77/0.0);*/
		
		System.out.println(0/0.0+""+0.0/0);
		
		System.out.println(Integer.parseInt("6v", 16));
	}
}
